# Generated by Django 3.1.4 on 2020-12-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='identification',
        ),
    ]
